import { Tender, UserProfile } from './types';

// Helper: create an end date X hours from now
function hoursFromNow(hours: number): string {
    const d = new Date();
    d.setHours(d.getHours() + hours);
    return d.toISOString();
}

export const MOCK_TENDERS: Tender[] = [
    {
        id: '1',
        title: 'סל קניות שבועי',
        description: 'סל קניות משפחתי הכולל מוצרי מזון בסיסיים לשבוע שלם.',
        imageUrl: 'https://cdn-icons-png.flaticon.com/512/3514/3514491.png',
        startingPrice: 350,
        targetPrice: 210,
        currentPrice: 315,
        endDate: hoursFromNow(8.5),
        currentParticipants: 84,
        targetParticipants: 100,
        category: 'מזון',
        status: 'OPEN',
        priceTiers: [
            { minParticipants: 10, discountPercent: 0 },
            { minParticipants: 25, discountPercent: 10 },
            { minParticipants: 50, discountPercent: 20 },
            { minParticipants: 75, discountPercent: 30 },
            { minParticipants: 100, discountPercent: 40 },
        ],
    },
    {
        id: '2',
        title: 'מוצרי ניקיון',
        description: 'חבילת מוצרי ניקיון לבית - כולל אבקת כביסה, סבון כלים ועוד.',
        imageUrl: 'https://cdn-icons-png.flaticon.com/512/2553/2553691.png',
        startingPrice: 120,
        targetPrice: 72,
        currentPrice: 108,
        endDate: hoursFromNow(2.25),
        currentParticipants: 45,
        targetParticipants: 80,
        category: 'מזון',
        status: 'OPEN',
        priceTiers: [
            { minParticipants: 10, discountPercent: 0 },
            { minParticipants: 25, discountPercent: 10 },
            { minParticipants: 50, discountPercent: 20 },
            { minParticipants: 75, discountPercent: 30 },
            { minParticipants: 80, discountPercent: 40 },
        ],
    },
    {
        id: '3',
        title: 'ירקות מהמשק',
        description: 'מבחר ירקות טריים ישירות מהחקלאי.',
        imageUrl: 'https://cdn-icons-png.flaticon.com/512/2329/2329865.png',
        startingPrice: 95,
        targetPrice: 57,
        currentPrice: 85,
        endDate: hoursFromNow(14),
        currentParticipants: 30,
        targetParticipants: 60,
        category: 'מזון',
        status: 'OPEN',
        priceTiers: [
            { minParticipants: 10, discountPercent: 0 },
            { minParticipants: 20, discountPercent: 10 },
            { minParticipants: 35, discountPercent: 20 },
            { minParticipants: 50, discountPercent: 30 },
            { minParticipants: 60, discountPercent: 40 },
        ],
    },
    {
        id: '4',
        title: 'פירות מהמשק',
        description: 'מבחר פירות עונתיים טריים ישירות מהחקלאי.',
        imageUrl: 'https://cdn-icons-png.flaticon.com/512/3194/3194766.png',
        startingPrice: 110,
        targetPrice: 66,
        currentPrice: 99,
        endDate: hoursFromNow(1.75),
        currentParticipants: 55,
        targetParticipants: 70,
        category: 'מזון',
        status: 'OPEN',
        priceTiers: [
            { minParticipants: 10, discountPercent: 0 },
            { minParticipants: 20, discountPercent: 10 },
            { minParticipants: 40, discountPercent: 20 },
            { minParticipants: 60, discountPercent: 30 },
            { minParticipants: 70, discountPercent: 40 },
        ],
    },
    {
        id: '5',
        title: 'תנור נינג\'ה',
        description: 'תנור אוויר חם נינג\'ה דגם AF300 - בישול בריא וקל.',
        imageUrl: 'https://cdn-icons-png.flaticon.com/512/3075/3075929.png',
        startingPrice: 650,
        targetPrice: 390,
        currentPrice: 585,
        endDate: hoursFromNow(8.5),
        currentParticipants: 22,
        targetParticipants: 50,
        category: 'חשמל',
        status: 'OPEN',
        priceTiers: [
            { minParticipants: 5, discountPercent: 0 },
            { minParticipants: 15, discountPercent: 10 },
            { minParticipants: 25, discountPercent: 20 },
            { minParticipants: 40, discountPercent: 30 },
            { minParticipants: 50, discountPercent: 40 },
        ],
    },
    {
        id: '6',
        title: 'מקרר',
        description: 'מקרר דו דלתי 520 ליטר עם מקפיא תחתון.',
        imageUrl: 'https://cdn-icons-png.flaticon.com/512/3474/3474360.png',
        startingPrice: 2200,
        targetPrice: 1320,
        currentPrice: 1980,
        endDate: hoursFromNow(2.25),
        currentParticipants: 12,
        targetParticipants: 30,
        category: 'חשמל',
        status: 'OPEN',
        priceTiers: [
            { minParticipants: 5, discountPercent: 0 },
            { minParticipants: 10, discountPercent: 10 },
            { minParticipants: 15, discountPercent: 20 },
            { minParticipants: 25, discountPercent: 30 },
            { minParticipants: 30, discountPercent: 40 },
        ],
    },
];

export const MOCK_USER: UserProfile = {
    id: 'u1',
    name: 'שרה כהן',
    email: 'sara@example.com',
    totalSavings: 2840,
    tenderHistory: [
        {
            id: 'h1',
            title: 'סל קניות, אזור מודיעין',
            date: '29/02/26',
            savings: 30,
            icon: 'shopping-cart',
        },
        {
            id: 'h2',
            title: 'מכרז פלזמה 46 אינץ\'',
            date: '14/03/26',
            savings: 100,
            icon: 'tv',
        },
        {
            id: 'h3',
            title: 'מכרז סל מוצרי ניקיון',
            date: '18/03/26',
            savings: 20,
            icon: 'local-laundry-service',
        },
    ],
};
